package com.revature.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T08:26:52.417-04:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "serviceTwo",
                  wsdlLocation = "http://localhost:8080/SOAPFunctions/display?wsdl",
                  targetNamespace = "http://service.revature.com/")
public class ServiceTwo_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.revature.com/", "serviceTwo");
    public final static QName ServiceTwoImplPort = new QName("http://service.revature.com/", "ServiceTwoImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/SOAPFunctions/display?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceTwo_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/SOAPFunctions/display?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceTwo_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceTwo_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceTwo_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServiceTwo_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiceTwo_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiceTwo_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServiceTwo
     */
    @WebEndpoint(name = "ServiceTwoImplPort")
    public ServiceTwo getServiceTwoImplPort() {
        return super.getPort(ServiceTwoImplPort, ServiceTwo.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceTwo
     */
    @WebEndpoint(name = "ServiceTwoImplPort")
    public ServiceTwo getServiceTwoImplPort(WebServiceFeature... features) {
        return super.getPort(ServiceTwoImplPort, ServiceTwo.class, features);
    }

}
