
package com.revature.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T08:26:52.375-04:00
 * Generated source version: 3.3.0
 *
 */
public final class ServiceTwo_ServiceTwoImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.revature.com/", "serviceTwo");

    private ServiceTwo_ServiceTwoImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ServiceTwo_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ServiceTwo_Service ss = new ServiceTwo_Service(wsdlURL, SERVICE_NAME);
        ServiceTwo port = ss.getServiceTwoImplPort();

        {
        System.out.println("Invoking multiplyName...");
        java.lang.String _multiplyName_arg0 = "";
        java.lang.String _multiplyName__return = port.multiplyName(_multiplyName_arg0);
        System.out.println("multiplyName.result=" + _multiplyName__return);


        }

        System.exit(0);
    }

}
