package com.revature.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T08:26:52.112-04:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://service.revature.com/", name = "ServiceOne")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceOne {

    @WebMethod
    @RequestWrapper(localName = "addTwoNumbers", targetNamespace = "http://service.revature.com/", className = "com.revature.service.AddTwoNumbers")
    @ResponseWrapper(localName = "addTwoNumbersResponse", targetNamespace = "http://service.revature.com/", className = "com.revature.service.AddTwoNumbersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int addTwoNumbers(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
