package com.revature.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-03-25T08:26:52.392-04:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://service.revature.com/", name = "ServiceTwo")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceTwo {

    @WebMethod
    @RequestWrapper(localName = "multiplyName", targetNamespace = "http://service.revature.com/", className = "com.revature.service.MultiplyName")
    @ResponseWrapper(localName = "multiplyNameResponse", targetNamespace = "http://service.revature.com/", className = "com.revature.service.MultiplyNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String multiplyName(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
